language: cpp

dist: trusty

apt:
  addons:
    sources:
      - george-edison55-cmake-3.x
    packages:
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTING=ON -DBUILD_VC=ON -DBUILD_UMESIMD=ON
  - make && make test
